ISSITES-5743/ISSITES-5744 public sites nav changes
allen-ziegenfus/liferay-portal pull request #13
Opened 2022-10-18 15:53 UTC by liaoethan

2022-10-18 19:58 UTC, allen-ziegenfus requested changes

2022-10-18 19:58 UTC, allen-ziegenfus commented on modules/apps/site-initializer/site-initializer-liferay-learn/src/main/resources/site-initializer/fragments/group/public-sites-navigation/fragments/public-sites-navigation/index.js
> +const menuButtonGroup = document.querySelector('.menu-button-group');
@liaoethan  These selectors are pretty non-specific to use on the whole document. You can instead just add `/* eslint-disable no-undef */` to ignore the fragmentElement error

2022-10-18 19:58 UTC, allen-ziegenfus commented on modules/apps/site-initializer/site-initializer-liferay-learn/src/main/resources/site-initializer/style-books/learn/frontend-tokens-values.json
> +		"cssVariableMapping": "btn-outline-hover-color",
This token does not exist in dialect when I searched. There are a lot of different hover tokens in dialect (48 tokens) did you not find any there you could use?

2022-10-18 23:34 UTC, liaoethan commented
Thanks @allen-ziegenfus, I made changes to the two suggestions you made above

2022-10-19 02:35 UTC, allen-ziegenfus commented
thanks @liaoethan  I had to squash this since there were too many commits: https://github.com/brianchandotcom/liferay-portal/pull/124843

2022-10-19 02:35 UTC, closed without merging